### ISSUE TITLE
Can't get included com connection on v1.1.3 it to work with Nano+tef module.

### ISSUE THREAD

**Issue by Overland-DX** [NoobishSVK/fm-dx-webserver#40] opened 2024-03-11 05:56 UTC
I can't get the new version (1.1.3) to work with fm-dx-tuner (arduino nano+tef6686 module.
It connects to the correct comport, but it doesn't look like fm-dx web server and fm-dx tuner are talking at all.
I have tested with esp32-spi (fw2.00.6) gray china model and everything seemed fine there.

**Comment by NoobishSVK** [comment] 2024-03-16 18:43
I made some changes in 1.1.4, though I don't think they will help. I'll look into it further.

**Comment by HME-Tef** [comment] 2024-03-18 08:11
> I made some changes in 1.1.4, though I don't think they will help. I'll look into it further.

Can you make a update for the Aduino Nano TEF6686?
Or what code can I put in the source to make it work?
The Nano's does work with XDR-GTK so the communication is good.

**Comment by Overland-DX** [comment] 2024-03-18 08:41
I tested with v1.1.4 and it still doesn't work. No stress, just using xdrd for now.

**Comment by DABtester** [comment] 2024-03-21 14:45
Same here, tested with 1.1.4 and does not connect. Would be great if this could be resolved.

**Comment by NoobishSVK** [comment] 2024-03-21 21:28
I have added one more command and it seems to work properly on my ESP32+TEF using Konrad's firmware. The update will be out in a few minutes.

**Comment by DABtester** [comment] 2024-03-22 07:56
ARDUINO tested with 1.1.6, not yet working

**Comment by Overland-DX** [comment] 2024-03-22 10:53
I also tested with 1.1.6, but it still doesn't work.

**Comment by NoobishSVK** [comment] 2024-03-28 21:51
I have asked @kkonradpl for the initialization commands and I have tried to introduce them. Please let me know if there's any change. 
On top of that, you may need to try to change the baud rate in case 115200 doesn't work in server/index.js

**Comment by Overland-DX** [comment] 2024-03-29 01:04
I have tested 19200, 38400, 57600 but no response. I was at 19200 when I went back to xdrd, but then I had to go back to 115200 for xdrd to work again.

**Comment by DABtester** [comment] 2024-04-01 10:14
Tested with 1.1.9, but unfortunately still no connection.

- Looked at the baud rate settings of the COM port (9600) and set 9600 in index.js
- Manually changed the baudrate of the COM to 115200 and changed index,js to 115200

Just so that we are on the same page: When running the setup/wizard, the device that we have to choose is TEF6686/TEA685X with USB cable as Tuner connection... Correct?

**Comment by NoobishSVK** [comment] 2024-04-05 22:39
@Overland-DX  Thanks for testing, I will have to consult this with @kkonradpl further.
@DABtester I see, the device chosen shouldn't matter - it seems like there might still be something missing in the serial init script. I will try to find more ways to fix this.

**Comment by NoobishSVK** [comment] 2024-07-16 08:32
I made some changes, would it be possible for you to check now?

**Comment by DABtester** [comment] 2024-07-16 14:34
Tested, but cannot get it to work.

Using XDRD in the middle at the moment, so no hurry

**Comment by Overland-DX** [comment] 2024-07-16 19:47
I also tested. I do not get a response when contacting directly. Via xdrd it works fine.

**Comment by NoobishSVK** [comment] 2024-07-18 13:20
Sjef made a commit that fixed the issue for him. Can you try now?

**Comment by DABtester** [comment] 2024-07-18 13:40
Tested - unfortunately doesn't work for me

**Comment by PE5PVB** [comment] 2024-07-18 14:09
I'll try to build a Arduino version tonight to find the cause.

**Comment by NoobishSVK** [comment] 2024-07-21 20:48
I tried to disable RTS/DTR on the serial port, that may fix the issue.

**Comment by NoobishSVK** [comment] 2024-08-02 11:30
Are there any changes as of the current (1.2.6a) version for you? 
@DABtester @Overland-DX

**Comment by Overland-DX** [comment] 2024-08-02 12:40
I updated to v 1.2.6a but it's still the same. Still no response when direct contact is selected in settings.

**Comment by Overland-DX** [comment] 2024-08-02 15:05
The pull request #76  from AmateurAudioDude seems to work with nano+tef.

**Comment by DABtester** [comment] 2024-08-02 16:45
Same here, version from AmateurAudioDude works with nano

**Comment by NoobishSVK** [comment] 2024-08-29 19:01
Amazing, in that case we can close it as this was included in the webserver. Thank you very much for being so patient!

**Closed by NoobishSVK** 2024-08-29 19:01 UTC
Labels: bug
